import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { listStudyPlans, generateStudyPlan, deleteStudyPlan } from "@/lib/study-plans.functions";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { BookMarked, Sparkles, BookOpen, ListChecks, CalendarDays, Trash2, Loader2 } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

export const Route = createFileRoute("/_authenticated/student/study-plans/")({
  component: StudyPlans,
  head: () => ({
    meta: [
      { title: "AI Study Plans | EduMind AI" },
      { name: "description", content: "Personalised study plans generated by your EduMind AI Tutor." },
      { property: "og:title", content: "AI Study Plans | EduMind AI" },
      { property: "og:description", content: "Personalised study plans generated by your EduMind AI Tutor." },
      { property: "og:type", content: "website" },
      { name: "twitter:card", content: "summary" },
    ],
  }),
});

function StudyPlans() {
  const list = useServerFn(listStudyPlans);
  const generate = useServerFn(generateStudyPlan);
  const remove = useServerFn(deleteStudyPlan);
  const qc = useQueryClient();
  const navigate = useNavigate();
  const [topic, setTopic] = useState("");

  const { data: plans = [] } = useQuery({ queryKey: ["study-plans"], queryFn: () => list() });

  const gen = useMutation({
    mutationFn: () => generate({ data: { topic: topic.trim() || undefined, days: 14 } }),
    onSuccess: (r) => {
      setTopic("");
      qc.invalidateQueries({ queryKey: ["study-plans"] });
      toast.success("Your AI Tutor built a new study plan");
      navigate({ to: "/student/study-plans/$id", params: { id: r.planId } });
    },
    onError: (e: Error) => toast.error(e.message),
  });

  const del = useMutation({
    mutationFn: (planId: string) => remove({ data: { planId } }),
    onSuccess: () => qc.invalidateQueries({ queryKey: ["study-plans"] }),
    onError: (e: Error) => toast.error(e.message),
  });

  return (
    <div className="space-y-6 p-6">
      <div>
        <h1 className="text-3xl font-bold">My Study Plans</h1>
        <p className="text-sm text-muted-foreground">Ask your AI Tutor to build a plan around your modules.</p>
      </div>

      <Card className="glass border-primary/20">
        <CardContent className="space-y-3 p-5">
          <div>
            <h2 className="text-xl font-semibold">AI-Generated Study Plans</h2>
            <p className="text-sm text-muted-foreground">Personalized study plans generated by your AI Tutor.</p>
          </div>
          <div className="flex flex-col gap-2 sm:flex-row">
            <Input
              value={topic}
              onChange={(e) => setTopic(e.target.value)}
              placeholder="Optional focus, e.g. prepare for INT316D exam"
            />
            <Button onClick={() => gen.mutate()} disabled={gen.isPending}>
              {gen.isPending ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Sparkles className="mr-2 h-4 w-4" />}
              {gen.isPending ? "Generating…" : "Generate with AI Tutor"}
            </Button>
          </div>
        </CardContent>
      </Card>

      {plans.length === 0 && !gen.isPending && (
        <p className="text-sm text-muted-foreground">No study plans yet — generate your first one above.</p>
      )}

      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">
        {plans.map((p) => (
          <Card key={p.id} className="glass transition-colors hover:border-primary/40">
            <CardContent className="space-y-3 p-5">
              <div className="flex items-start justify-between">
                <div className="rounded-xl bg-gradient-to-br from-primary to-accent p-2.5">
                  <BookMarked className="h-5 w-5 text-primary-foreground" />
                </div>
                <div className="flex items-center gap-1">
                  {p.ai_generated && (
                    <span className="flex items-center gap-1 rounded-full bg-primary/15 px-2.5 py-1 text-xs text-primary">
                      <Sparkles className="h-3 w-3" /> AI Generated
                    </span>
                  )}
                  <Button
                    size="icon"
                    variant="ghost"
                    className="h-7 w-7 text-muted-foreground hover:text-destructive"
                    onClick={() => del.mutate(p.id)}
                  >
                    <Trash2 className="h-3.5 w-3.5" />
                  </Button>
                </div>
              </div>

              <Link to="/student/study-plans/$id" params={{ id: p.id }} className="block space-y-2">
                <div className="text-lg font-semibold">{p.title}</div>
                {p.qualification_title && (
                  <div className="flex items-center gap-1.5 text-sm text-muted-foreground">
                    <BookOpen className="h-4 w-4" /> {p.qualification_title}
                  </div>
                )}
                {p.description && <p className="text-sm text-muted-foreground">{p.description}</p>}
                <div className="flex items-center justify-between text-xs text-muted-foreground">
                  <span className="flex items-center gap-1.5">
                    <ListChecks className="h-3.5 w-3.5" /> {p.taskCount} tasks
                  </span>
                  <span className="flex items-center gap-1.5">
                    <CalendarDays className="h-3.5 w-3.5" />
                    {new Date(p.created_at).toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" })}
                  </span>
                </div>
                <div>
                  <div className="mb-1 flex justify-between text-xs text-muted-foreground">
                    <span>Progress</span>
                    <span>{p.progress}%</span>
                  </div>
                  <div className="h-2 overflow-hidden rounded-full bg-muted">
                    <div
                      className="h-full rounded-full bg-gradient-to-r from-primary to-accent"
                      style={{ width: `${p.progress}%` }}
                    />
                  </div>
                </div>
              </Link>
            </CardContent>
          </Card>
        ))}
      </div>
    </div>
  );
}
